<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ParcheggioConf {
	private $parcheggio_conf_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'parcheggio_conf_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'parcheggio_conf_page_init' ) );
	}

	public function parcheggio_conf_add_plugin_page() {
		add_menu_page(
			'Netparking', // page_title
			'Configurazione Netparking', // menu_title
			'manage_options', // capability
			'parcheggio-conf', // menu_slug
			array( $this, 'parcheggio_conf_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			3 // position
		);
	}

	public function parcheggio_conf_create_admin_page() {
		$this->parcheggio_conf_options = get_option( 'parcheggio_conf_option_name' ); ?>

		<div class="wrap">
			<h2>Netparking Configurazione</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php" class="parc_conf_options">
				<?php
					settings_fields( 'parcheggio_conf_option_group' );
					do_settings_sections( 'parcheggio-conf-admin' );
					submit_button();
				?>
			</form>
			
		</div>
	<?php }

	public function parcheggio_conf_page_init() {
		register_setting(
			'parcheggio_conf_option_group', // option_group
			'parcheggio_conf_option_name', // option_name
			array( $this, 'parcheggio_conf_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'parcheggio_conf_setting_section', // id
			'Settings', // title
			array( $this, 'parcheggio_conf_section_info' ), // callback
			'parcheggio-conf-admin' // page
		);

		add_settings_field(
			'partner_css_0', // id
			'Css personalizzato', // title
			array( $this, 'partner_css_0_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

		add_settings_field(
			'partner_key', // id
			'Partner API KEY', // title
			array( $this, 'partner_key_1_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

        add_settings_field(
			'partner_id', // id
			'Partner ID', // title
			array( $this, 'partner_id_1_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

        add_settings_field(
			'pagina_ricerca_id', // id
			'Pagina ID della ricerca', // title
			array( $this, 'pagina_id_1_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

        add_settings_field(
			'pagina_prenotazione_id', // id
			'Pagina ID prenotazione', // title
			array( $this, 'pagina_id_2_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

        add_settings_field(
			'google_key', // id
			'Google Recpacha Key', // title
			array( $this, 'google_key_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

		add_settings_field(
			'car_icon', // id
			'Car Icon', // title
			array( $this, 'car_icon_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

		add_settings_field(
			'motorcycle_icon', // id
			'Motorcycle Icon', // title
			array( $this, 'motorcycle_icon_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);
		
		add_settings_field(
			'van_icon', // id
			'Van Icon', // title
			array( $this, 'van_icon_callback' ), // callback
			'parcheggio-conf-admin', // page
			'parcheggio_conf_setting_section' // section
		);

	}

	public function parcheggio_conf_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['partner_css_0'] ) ) {
			$sanitary_values['partner_css_0'] = ( $input['partner_css_0'] );
		}

		if ( isset( $input['partner_key'] ) ) {
			$sanitary_values['partner_key'] = sanitize_text_field( $input['partner_key'] );
		}

        if ( isset( $input['partner_id'] ) ) {
			$sanitary_values['partner_id'] = sanitize_text_field( $input['partner_id'] );
		}

        if ( isset( $input['pagina_ricerca_id'] ) ) {
			$sanitary_values['pagina_ricerca_id'] = sanitize_text_field( $input['pagina_ricerca_id'] );
		}

        if ( isset( $input['pagina_prenotazione_id'] ) ) {
			$sanitary_values['pagina_prenotazione_id'] = sanitize_text_field( $input['pagina_prenotazione_id'] );
		}

        if ( isset( $input['google_key'] ) ) {
			$sanitary_values['google_key'] = sanitize_text_field( $input['google_key'] );
		}
		if ( isset( $input['vehicle_icon'] ) ) {
			$sanitary_values['vehicle_icon'] = sanitize_text_field( $input['vehicle_icon'] );
		}

		if ( isset( $input['select_car_option_0'] ) ) {
			$sanitary_values['select_car_option_0'] = $input['select_car_option_0'];
		}
		if ( isset( $input['select_motor_option_0'] ) ) {
			$sanitary_values['select_motor_option_0'] = $input['select_motor_option_0'];
		}
		if ( isset( $input['select_van_option_0'] ) ) {
			$sanitary_values['select_van_option_0'] = $input['select_van_option_0'];
		}

		return $sanitary_values;
	}

	public function parcheggio_conf_section_info() {

	}

	public function partner_css_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="parcheggio_conf_option_name[partner_css_0]" id="partner_css_0">%s</textarea>',
			isset( $this->parcheggio_conf_options['partner_css_0'] ) ? esc_attr( $this->parcheggio_conf_options['partner_css_0']) : ''
		);
	}

	public function partner_key_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="parcheggio_conf_option_name[partner_key]" id="partner_key" value="%s">',
			isset( $this->parcheggio_conf_options['partner_key'] ) ? esc_attr( $this->parcheggio_conf_options['partner_key']) : ''
		);
	}

    public function partner_id_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="parcheggio_conf_option_name[partner_id]" id="partner_id" value="%s">',
			isset( $this->parcheggio_conf_options['partner_id'] ) ? esc_attr( $this->parcheggio_conf_options['partner_id']) : ''
		);
	}

    public function pagina_id_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="parcheggio_conf_option_name[pagina_ricerca_id]" id="pagina_ricerca_id" value="%s">',
			isset( $this->parcheggio_conf_options['pagina_ricerca_id'] ) ? esc_attr( $this->parcheggio_conf_options['pagina_ricerca_id']) : ''
		);
	}

    public function pagina_id_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="parcheggio_conf_option_name[pagina_prenotazione_id]" id="pagina_prenotazione_id" value="%s">',
			isset( $this->parcheggio_conf_options['pagina_prenotazione_id'] ) ? esc_attr( $this->parcheggio_conf_options['pagina_prenotazione_id']) : ''
		);
	}

    public function google_key_callback() {
		printf(
			'<input class="regular-text" type="text" name="parcheggio_conf_option_name[google_key]" id="google_key" value="%s">',
			isset( $this->parcheggio_conf_options['google_key'] ) ? esc_attr( $this->parcheggio_conf_options['google_key']) : ''
		);
	}

	public function car_icon_callback() {

		$options = get_option( 'parcheggio_conf_option_name' );
		// var_dump($options);
		$select_car = $options['select_car_option_0'];
		?>

		<fieldset>
			<?php $checked = ( $select_car === 'fas fa-baby-carriage' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-0">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-0" value="fas fa-baby-carriage" <?php echo $checked ?>> 
				<i class="fas fa-baby-carriage" aria-hidden="true"></i>
			</label>
			<?php $checked = ( $select_car === 'fas fa-car' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-1">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-1" value="fas fa-car"  <?php echo $checked ?>>
				<i class="fas fa-car" aria-hidden="true"></i>
			</label>
			<?php $checked = ( $select_car === 'fas fa-bus-alt' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-3">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-3" value="fas fa-bus-alt"  <?php echo $checked ?>> 
				<i class="fas fa-bus-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-bus' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-4">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-4" value="fas fa-bus"  <?php echo $checked ?>> 
				<i class="fas fa-bus" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-car-alt' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-5">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-5" value="fas fa-car-alt"  <?php echo $checked ?>> 
				<i class="fas fa-car-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-car-side' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-6">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-6" value="fas fa-car-side"  <?php echo $checked ?>> 
				<i class="fas fa-car-side" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-shuttle-van' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-7">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-7" value="fas fa-shuttle-van"   <?php echo $checked ?>> 
				<i class="fas fa-shuttle-van" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-subway' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-8">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-8" value="fas fa-subway"  <?php echo $checked ?>> 
				<i class="fas fa-subway" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-taxi' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-9">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-9" value="fas fa-taxi"  <?php echo $checked ?>> 
				<i class="fas fa-taxi" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-train' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-10">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-10" value="fas fa-train"  <?php echo $checked ?>> 
				<i class="fas fa-train" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-tram' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-11">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-11" value="fas fa-tram"  <?php echo $checked ?>> 
				<i class="fas fa-tram" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-truck' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-12">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-12" value="fas fa-truck"  <?php echo $checked ?>> 
				<i class="fas fa-truck" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_car === 'fas fa-truck-monster' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-13">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-13" value="fas fa-truck-monster"  <?php echo $checked ?>> 
				<i class="fas fa-truck-monster" aria-hidden="true"></i> 
			</label>

			<?php $checked = ( $select_car === 'fas fa-truck-pickup' ) ? 'checked' : '' ; ?>
			<label for="select_car_option_0-14">
				<input type="radio" name="parcheggio_conf_option_name[select_car_option_0]" id="select_car_option_0-14" value="fas fa-truck-pickup"  <?php echo $checked ?>> 
				<i class="fas fa-truck-pickup" aria-hidden="true"></i> 
			</label>
		</fieldset> 
		<?php
	}


	public function van_icon_callback() {
		
		$options = get_option( 'parcheggio_conf_option_name' );
		$select_van = $options['select_van_option_0'];

		?>

		<fieldset>
			<?php $checked = (  $select_van === 'fas fa-car' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-1">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-1" value="fas fa-car" <?php echo $checked ?>>
				<i class="fas fa-car" aria-hidden="true"></i>
			</label>
			<?php $checked = (  $select_van === 'fas fa-bus-alt' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-3">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-3" value="fas fa-bus-alt" <?php echo $checked ?>> 
				<i class="fas fa-bus-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-bus' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-4">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-4" value="fas fa-bus" <?php echo $checked ?>> 
				<i class="fas fa-bus" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fa-solid fa-caravan' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-15">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-15" value="fa-solid fa-caravan" <?php echo $checked ?>> 
				<i class="fa-solid fa-caravan"></i> 
			</label>
			<?php $checked = ( $select_van === 'fa-solid fa-truck-moving' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-16">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-16" value="fa-solid fa-truck-moving" <?php echo $checked ?>> 
				<i class="fa-solid fa-truck-moving"></i>
			</label>
			<?php $checked = ( $select_van === 'fas fa-car-alt' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-5">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-5" value="fas fa-car-alt" <?php echo $checked ?>> 
				<i class="fas fa-car-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van == 'fas fa-car-side' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-6">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-6" value="fas fa-car-side" <?php echo $checked ?>> 
				<i class="fas fa-car-side" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-shuttle-van' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-7">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-7" value="fas fa-shuttle-van" <?php echo $checked ?>> 
				<i class="fas fa-shuttle-van" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-subway' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-8">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-8" value="fas fa-subway" <?php echo $checked ?>> 
				<i class="fas fa-subway" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-taxi' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-9">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-9" value="fas fa-taxi" <?php echo $checked ?>> 
				<i class="fas fa-taxi" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-train' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-10">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-10" value="fas fa-train" <?php echo $checked ?>> 
				<i class="fas fa-train" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-tram' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-11">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-11" value="fas fa-tram" <?php echo $checked ?>> 
				<i class="fas fa-tram" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-truck' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-12">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-12" value="fas fa-truck" <?php echo $checked ?>> 
				<i class="fas fa-truck" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_van === 'fas fa-truck-monster' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-13">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-13" value="fas fa-truck-monster" <?php echo $checked ?>> 
				<i class="fas fa-truck-monster" aria-hidden="true"></i> 
			</label>

			<?php $checked = ( $select_van === 'fas fa-truck-pickup' ) ? 'checked' : '' ; ?>
			<label for="select_van_option_0-14">
				<input type="radio" name="parcheggio_conf_option_name[select_van_option_0]" id="select_van_option_0-14" value="fas fa-truck-pickup" <?php echo $checked ?>> 
				<i class="fas fa-truck-pickup" aria-hidden="true"></i> 
			</label>
		</fieldset> 
		<?php
	}


	public function motorcycle_icon_callback() {
		
		$options = get_option( 'parcheggio_conf_option_name' );
		$select_motor = $options['select_motor_option_0'];

		?>

		<fieldset>
		<?php $checked = ( $select_motor === 'fas fa-bicycle' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-0">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-0" value="fas fa-bicycle" <?php echo $checked ?> > 
				<i class="fas fa-bicycle" aria-hidden="true"></i>
			</label>
			<?php $checked = ( $select_motor === 'fas fa-motorcycle' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-0">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-0" value="fas fa-motorcycle" <?php echo $checked ?> > 
				<i class="fas fa-motorcycle" aria-hidden="true"></i>
			</label>
			<?php $checked = (  $select_motor === 'fas fa-car' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-1">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-1" value="fas fa-car" <?php echo $checked ?> >
				<i class="fas fa-car" aria-hidden="true"></i>
			</label>
			<?php $checked = (  $select_motor === 'fas fa-bus-alt' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-3">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-3" value="fas fa-bus-alt" <?php echo $checked ?> > 
				<i class="fas fa-bus-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-bus' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-4">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-4" value="fas fa-bus" <?php echo $checked ?> > 
				<i class="fas fa-bus" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-car-alt' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-5">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-5" value="fas fa-car-alt" <?php echo $checked ?> > 
				<i class="fas fa-car-alt" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor == 'fas fa-car-side' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-6">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-6" value="fas fa-car-side" <?php echo $checked ?> > 
				<i class="fas fa-car-side" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-shuttle-van' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-7">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-7" value="fas fa-shuttle-van" <?php echo $checked ?> > 
				<i class="fas fa-shuttle-van" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-subway' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-8">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-8" value="fas fa-subway" <?php echo $checked ?> > 
				<i class="fas fa-subway" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-taxi' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-9">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-9" value="fas fa-taxi" <?php echo $checked ?> > 
				<i class="fas fa-taxi" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-train' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-10">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-10" value="fas fa-train" <?php echo $checked ?> > 
				<i class="fas fa-train" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-tram' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-11">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-11" value="fas fa-tram" <?php echo $checked ?> > 
				<i class="fas fa-tram" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-truck' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-12">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-12" value="fas fa-truck" <?php echo $checked ?> > 
				<i class="fas fa-truck" aria-hidden="true"></i> 
			</label>
			<?php $checked = ( $select_motor === 'fas fa-truck-monster' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-13">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-13" value="fas fa-truck-monster" <?php echo $checked ?> > 
				<i class="fas fa-truck-monster" aria-hidden="true"></i> 
			</label>

			<?php $checked = ( $select_motor === 'fas fa-truck-pickup' ) ? 'checked' : '' ; ?>
			<label for="select_motor_option_0-14">
				<input type="radio" name="parcheggio_conf_option_name[select_motor_option_0]" id="select_motor_option_0-14" value="fas fa-truck-pickup" <?php echo $checked ?> > 
				<i class="fas fa-truck-pickup" aria-hidden="true"></i> 
			</label>
		</fieldset> 
		<?php
	}
}
if ( is_admin() )
	$ParcheggioConf = new ParcheggioConf();

/*
 * Retrieve this value with:
 * $parcheggio_conf_options = get_option( 'parcheggio_conf_option_name' ); // Array of All Options
 * $email_registrazione_0 = $parcheggio_conf_options['email_registrazione_0']; // Email Registrazione
 * $oggetto_1 = $parcheggio_conf_options['oggetto_1']; // Oggetto
 * $notifica_email_2 = $parcheggio_conf_options['notifica_email_2']; // Notifica Email
 * $notifica_email_admin_3 = $parcheggio_conf_options['notifica_email_admin_3']; // Notifica email admin
 * $select_car_option_0 = $test_options['select_car_option_0'];
 */


